---
# =============================================================================
# PLAYBOOK 06: Template Basics - Dynamic Configuration Files
# =============================================================================
# WHAT YOU'LL LEARN:
#   - Using Jinja2 templates with the 'template' module
#   - Template syntax: variables, loops, conditionals
#   - Creating dynamic configuration files
#   - Template file best practices
#
# REAL-WORLD USE: Like creating .env files for your garden-agent project!
#
# RUN THIS PLAYBOOK:
#   ansible-playbook educational/06_template_basics.yml
# =============================================================================

- name: Template Fundamentals
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    # Application configuration variables
    app_name: "Garden Agent"
    app_port: 8080
    debug_mode: true

    # Database configuration
    database:
      host: localhost
      port: 5432
      name: garden_db
      user: garden_user
      # In production, use Ansible Vault for passwords!
      password: "secret123"

    # Feature flags (like your OpenAI integration)
    features:
      - name: openai_integration
        enabled: true
      - name: logging
        enabled: true
      - name: caching
        enabled: false

    # Environment (development, staging, production)
    environment: development

    # Allowed hosts list
    allowed_hosts:
      - localhost
      - 127.0.0.1
      - garden.example.com

    # Output directory for our examples
    template_dir: "/tmp/ansible-templates"

  tasks:

    # =========================================================================
    # SETUP: Create output directory
    # =========================================================================
    - name: Create directory for template output
      ansible.builtin.file:
        path: "{{ template_dir }}"
        state: directory
        mode: '0755'

    # =========================================================================
    # UNDERSTANDING TEMPLATES
    # =========================================================================
    # Templates use Jinja2 syntax:
    #   {{ variable }}      - insert a variable
    #   {% if/for %}        - control structures
    #   {# comment #}       - template comments
    #   {{ var | filter }}  - apply filters

    # =========================================================================
    # TASK 1: Create a simple template inline
    # =========================================================================
    # For small templates, you can use 'copy' with 'content'
    - name: Create a simple .env file (like garden-agent!)
      ansible.builtin.copy:
        content: |
          # Environment Configuration
          # Generated by Ansible on {{ ansible_date_time.date }}

          # Application Settings
          APP_NAME={{ app_name }}
          APP_PORT={{ app_port }}
          DEBUG={{ debug_mode | lower }}
          ENVIRONMENT={{ environment }}

          # Database Connection
          DB_HOST={{ database.host }}
          DB_PORT={{ database.port }}
          DB_NAME={{ database.name }}
          DB_USER={{ database.user }}
          DB_PASSWORD={{ database.password }}

          # This is similar to how you create .env files
          # in your installgitcurl.yml for garden-agent!
        dest: "{{ template_dir }}/app.env"
        mode: '0640'
      # RESULT: Creates a .env file with variables substituted

    # =========================================================================
    # TASK 2: Template with conditionals
    # =========================================================================
    - name: Create config with conditional sections
      ansible.builtin.copy:
        content: |
          # Application Configuration
          # Mode: {{ environment }}

          server {
              port = {{ app_port }}
              {% if debug_mode %}
              # Debug mode is ON
              log_level = DEBUG
              error_details = true
              {% else %}
              # Production mode
              log_level = INFO
              error_details = false
              {% endif %}
          }

          {% if environment == 'production' %}
          # Production-specific settings
          cache_enabled = true
          ssl_required = true
          {% else %}
          # Development/staging settings
          cache_enabled = false
          ssl_required = false
          {% endif %}
        dest: "{{ template_dir }}/server.conf"
        mode: '0644'

    # =========================================================================
    # TASK 3: Template with loops
    # =========================================================================
    - name: Create config with looped sections
      ansible.builtin.copy:
        content: |
          # Feature Configuration
          # Enabled features listed below

          [features]
          {% for feature in features %}
          {% if feature.enabled %}
          {{ feature.name }} = enabled
          {% else %}
          # {{ feature.name }} = disabled
          {% endif %}
          {% endfor %}

          [allowed_hosts]
          {% for host in allowed_hosts %}
          host_{{ loop.index }} = {{ host }}
          {% endfor %}

          # Loop variables available:
          # loop.index    - current iteration (1-based)
          # loop.index0   - current iteration (0-based)
          # loop.first    - True if first iteration
          # loop.last     - True if last iteration
          # loop.length   - total number of items
        dest: "{{ template_dir }}/features.conf"
        mode: '0644'

    # =========================================================================
    # TASK 4: Using Jinja2 filters
    # =========================================================================
    - name: Demonstrate Jinja2 filters in templates
      ansible.builtin.copy:
        content: |
          # Jinja2 Filter Examples
          # ======================

          # Original value: {{ app_name }}

          # String filters:
          upper:      {{ app_name | upper }}
          lower:      {{ app_name | lower }}
          title:      {{ app_name | title }}
          replace:    {{ app_name | replace(' ', '_') }}
          length:     {{ app_name | length }} characters

          # List filters:
          hosts_count: {{ allowed_hosts | length }}
          first_host:  {{ allowed_hosts | first }}
          last_host:   {{ allowed_hosts | last }}
          joined:      {{ allowed_hosts | join(', ') }}

          # Default values (very useful!):
          missing_var: {{ undefined_var | default('not set') }}

          # Number filters:
          port_plus_100: {{ app_port + 100 }}

          # Boolean filters:
          debug_yesno: {{ debug_mode | ternary('yes', 'no') }}

          # Date/time (from gathered facts):
          today: {{ ansible_date_time.date }}
          time:  {{ ansible_date_time.time }}
        dest: "{{ template_dir }}/filters_demo.txt"
        mode: '0644'

    # =========================================================================
    # TASK 5: Create an nginx-style config
    # =========================================================================
    - name: Create sample nginx config
      ansible.builtin.copy:
        content: |
          # Nginx Configuration for {{ app_name }}
          # Generated by Ansible

          upstream app_backend {
              server 127.0.0.1:{{ app_port }};
          }

          server {
              listen 80;
              server_name {% for host in allowed_hosts %}{{ host }}{% if not loop.last %} {% endif %}{% endfor %};

              {% if environment == 'production' %}
              # Redirect to HTTPS in production
              return 301 https://$host$request_uri;
              {% else %}
              location / {
                  proxy_pass http://app_backend;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
              {% endif %}

              # Health check endpoint
              location /health {
                  access_log off;
                  return 200 'OK';
              }
          }
        dest: "{{ template_dir }}/nginx.conf"
        mode: '0644'

    # =========================================================================
    # TASK 6: Create a docker-compose template
    # =========================================================================
    # Similar to what you might use for garden-agent!
    - name: Create docker-compose template
      ansible.builtin.copy:
        content: |
          # Docker Compose for {{ app_name }}
          # Generated by Ansible on {{ ansible_hostname }}

          version: '3.8'

          services:
            app:
              build: .
              container_name: {{ app_name | lower | replace(' ', '-') }}
              ports:
                - "{{ app_port }}:{{ app_port }}"
              environment:
                - APP_NAME={{ app_name }}
                - DEBUG={{ debug_mode | lower }}
                - DB_HOST={{ database.host }}
                - DB_PORT={{ database.port }}
          {% if features | selectattr('name', 'equalto', 'openai_integration') | selectattr('enabled') | list | length > 0 %}
                # OpenAI integration enabled
                - OPENAI_API_KEY=${OPENAI_API_KEY}
          {% endif %}
              restart: unless-stopped
          {% if environment != 'development' %}
              logging:
                driver: json-file
                options:
                  max-size: "10m"
                  max-file: "3"
          {% endif %}

          networks:
            default:
              name: {{ app_name | lower | replace(' ', '-') }}-network
        dest: "{{ template_dir }}/docker-compose.yml"
        mode: '0644'
      # RESULT: A dynamic docker-compose.yml based on your variables!

    # =========================================================================
    # TASK 7: Show created files
    # =========================================================================
    - name: Read and display the .env file
      ansible.builtin.command:
        cmd: "cat {{ template_dir }}/app.env"
      register: env_content
      changed_when: false

    - name: Show .env file contents
      ansible.builtin.debug:
        msg: "{{ env_content.stdout_lines }}"

    # =========================================================================
    # TASK 8: List all created templates
    # =========================================================================
    - name: List template files created
      ansible.builtin.find:
        paths: "{{ template_dir }}"
        patterns: "*"
      register: template_files

    - name: Display template files
      ansible.builtin.debug:
        msg: "Created: {{ item.path }}"
      loop: "{{ template_files.files }}"
      loop_control:
        label: "{{ item.path | basename }}"

    # =========================================================================
    # NOTE: Using external template files
    # =========================================================================
    # In production, put templates in files with .j2 extension:
    #
    # templates/
    #   app.conf.j2
    #   nginx.conf.j2
    #
    # Then use the template module:
    #
    # - name: Deploy config from template file
    #   ansible.builtin.template:
    #     src: templates/app.conf.j2   # Source template
    #     dest: /etc/app/app.conf      # Destination on target
    #     mode: '0644'
    #     owner: root
    #     group: root
    #     # validate: /usr/sbin/nginx -t -c %s  # Optional validation
    #
    # Benefits of external templates:
    # - Easier to maintain complex templates
    # - Can use version control effectively
    # - Syntax highlighting in editors

    # =========================================================================
    # SUMMARY
    # =========================================================================
    - name: Lesson Summary
      ansible.builtin.debug:
        msg:
          - "============================================"
          - "  TEMPLATE BASICS COMPLETE"
          - "============================================"
          - ""
          - "KEY CONCEPTS LEARNED:"
          - "  - {{ variable }} - insert variables"
          - "  - {% if/for %} - control structures"
          - "  - Filters: upper, lower, default, join"
          - "  - Loop variables: loop.index, loop.first"
          - "  - template module vs copy with content"
          - ""
          - "YOUR PROJECT CONNECTION:"
          - "  Your installgitcurl.yml uses this to create"
          - "  the .env file with OPENAI_API_KEY!"
          - ""
          - "FILES CREATED IN: {{ template_dir }}"
          - ""
          - "NEXT: Try 07_conditionals.yml"
