---
# =============================================================================
# PLAYBOOK 15: Vault Secrets - Secure Credential Management
# =============================================================================
# WHAT YOU'LL LEARN:
#   - What Ansible Vault is and why it matters
#   - Encrypting and decrypting files
#   - Encrypting variables inline
#   - Using vault passwords
#   - Best practices for secrets management
#
# REAL-WORLD USE: Storing your OPENAI_API_KEY securely!
#
# NOTE: This playbook DEMONSTRATES vault concepts.
# To actually use vault, you need the ansible-vault command.
#
# RUN THIS PLAYBOOK:
#   ansible-playbook educational/15_vault_secrets.yml
# =============================================================================

- name: Vault Secrets - Secure Your Credentials
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Demo variables (in real use, these would be vaulted!)
    demo_api_key: "sk-demo-not-real-key-12345"
    demo_db_password: "super_secret_password"

    # Demo directory
    vault_demo_dir: "/tmp/ansible-vault-demo"

  tasks:

    # =========================================================================
    # SETUP
    # =========================================================================
    - name: Create demo directory
      ansible.builtin.file:
        path: "{{ vault_demo_dir }}"
        state: directory
        mode: '0755'

    # =========================================================================
    # UNDERSTANDING VAULT
    # =========================================================================

    # -------------------------------------------------------------------------
    # TASK 1: What is Ansible Vault?
    # -------------------------------------------------------------------------
    - name: Explain Ansible Vault
      ansible.builtin.debug:
        msg: |
          WHAT IS ANSIBLE VAULT?
          ======================

          Ansible Vault encrypts sensitive data so you can:
          - Store secrets in version control (safely!)
          - Share playbooks without exposing credentials
          - Meet security compliance requirements

          WITHOUT VAULT (DANGEROUS!):
            vars:
              api_key: "sk-real-key-exposed-in-git"

          WITH VAULT (SECURE!):
            vars:
              api_key: !vault |
                $ANSIBLE_VAULT;1.1;AES256
                6532...encrypted...data...

          Your OPENAI_API_KEY should use vault!

    # =========================================================================
    # VAULT COMMANDS
    # =========================================================================

    # -------------------------------------------------------------------------
    # TASK 2: Creating encrypted files
    # -------------------------------------------------------------------------
    - name: Show vault create command
      ansible.builtin.debug:
        msg: |
          CREATING ENCRYPTED FILES:
          =========================

          # Create a new encrypted file
          ansible-vault create secrets.yml

          # This opens an editor. Add your secrets:
          api_key: sk-your-real-key-here
          db_password: your_db_password
          ssh_private_key: |
            -----BEGIN RSA PRIVATE KEY-----
            ...
            -----END RSA PRIVATE KEY-----

          # Save and close - file is now encrypted!

    # -------------------------------------------------------------------------
    # TASK 3: Encrypting existing files
    # -------------------------------------------------------------------------
    - name: Show vault encrypt command
      ansible.builtin.debug:
        msg: |
          ENCRYPTING EXISTING FILES:
          ==========================

          # Encrypt an existing plaintext file
          ansible-vault encrypt secrets.yml

          # The file is now encrypted in place!
          # Original content is replaced with encrypted version.

    # -------------------------------------------------------------------------
    # TASK 4: Viewing and editing encrypted files
    # -------------------------------------------------------------------------
    - name: Show vault view and edit
      ansible.builtin.debug:
        msg: |
          VIEWING & EDITING:
          ==================

          # View encrypted file (read-only)
          ansible-vault view secrets.yml

          # Edit encrypted file (opens editor)
          ansible-vault edit secrets.yml

          # The file stays encrypted on disk!

    # -------------------------------------------------------------------------
    # TASK 5: Decrypting files
    # -------------------------------------------------------------------------
    - name: Show vault decrypt command
      ansible.builtin.debug:
        msg: |
          DECRYPTING FILES:
          =================

          # Permanently decrypt a file
          ansible-vault decrypt secrets.yml

          # WARNING: File is now in plaintext!
          # Don't commit to git after this!

          # Re-encrypt when done
          ansible-vault encrypt secrets.yml

    # =========================================================================
    # USING VAULT WITH PLAYBOOKS
    # =========================================================================

    # -------------------------------------------------------------------------
    # TASK 6: Running playbooks with vault
    # -------------------------------------------------------------------------
    - name: Show running with vault password
      ansible.builtin.debug:
        msg: |
          RUNNING VAULTED PLAYBOOKS:
          ==========================

          Option 1: Prompt for password
          -----------------------------
          ansible-playbook site.yml --ask-vault-pass

          Option 2: Password file
          -----------------------
          echo 'my_vault_password' > ~/.vault_pass
          chmod 600 ~/.vault_pass
          ansible-playbook site.yml --vault-password-file ~/.vault_pass

          Option 3: Environment variable
          ------------------------------
          export ANSIBLE_VAULT_PASSWORD_FILE=~/.vault_pass
          ansible-playbook site.yml

          Option 4: ansible.cfg
          ---------------------
          [defaults]
          vault_password_file = ~/.vault_pass

    # =========================================================================
    # VAULT BEST PRACTICES
    # =========================================================================

    # -------------------------------------------------------------------------
    # TASK 7: File organization
    # -------------------------------------------------------------------------
    - name: Show vault file organization
      ansible.builtin.debug:
        msg: |
          ORGANIZING VAULT FILES:
          =======================

          Recommended structure:

          project/
          ├── playbooks/
          │   └── deploy.yml
          ├── group_vars/
          │   ├── all/
          │   │   ├── vars.yml        # Non-sensitive variables
          │   │   └── vault.yml       # ENCRYPTED - sensitive vars
          │   └── production/
          │       ├── vars.yml
          │       └── vault.yml       # Production secrets
          ├── host_vars/
          │   └── webserver1/
          │       └── vault.yml       # Host-specific secrets
          └── .vault_pass             # Vault password (NOT in git!)

          IMPORTANT: Add .vault_pass to .gitignore!

    # -------------------------------------------------------------------------
    # TASK 8: Variable naming convention
    # -------------------------------------------------------------------------
    - name: Show variable naming best practices
      ansible.builtin.debug:
        msg: |
          VARIABLE NAMING CONVENTION:
          ===========================

          Prefix vaulted variables for clarity:

          # In group_vars/all/vault.yml (encrypted)
          vault_db_password: "secret123"
          vault_api_key: "sk-xyz..."
          vault_ssh_private_key: |
            -----BEGIN RSA PRIVATE KEY-----
            ...

          # In group_vars/all/vars.yml (plain)
          db_password: "{{ vault_db_password }}"
          api_key: "{{ vault_api_key }}"

          Benefits:
          - Easy to see what's vaulted
          - Centralized secret management
          - Clear separation of concerns

    # =========================================================================
    # ENCRYPTING STRINGS (INLINE VAULT)
    # =========================================================================

    # -------------------------------------------------------------------------
    # TASK 9: Encrypt single string
    # -------------------------------------------------------------------------
    - name: Show encrypting single strings
      ansible.builtin.debug:
        msg: |
          ENCRYPTING SINGLE STRINGS:
          ==========================

          # Encrypt a single value
          ansible-vault encrypt_string 'my_secret_password' --name 'db_password'

          Output:
          db_password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            61626364...

          # Paste this directly in your vars file!

          # For your OpenAI key:
          ansible-vault encrypt_string 'sk-your-real-key' --name 'openai_key'

    # =========================================================================
    # PRACTICAL EXAMPLE: GARDEN-AGENT SECRETS
    # =========================================================================

    # -------------------------------------------------------------------------
    # TASK 10: Securing garden-agent deployment
    # -------------------------------------------------------------------------
    - name: Show secure garden-agent setup
      ansible.builtin.debug:
        msg: |
          SECURING YOUR GARDEN-AGENT:
          ===========================

          Currently in installgitcurl.yml:
          --------------------------------
          vars:
            openai_key: "{{ lookup('env', 'OPENAI_API_KEY') }}"

          This is OK but relies on environment variable being set.

          BETTER - Using Vault:
          ---------------------

          Step 1: Create vault file
          $ ansible-vault create group_vars/all/vault.yml

          Add:
            vault_openai_api_key: "sk-your-real-key-here"

          Step 2: Reference in playbook
          vars:
            openai_key: "{{ vault_openai_api_key }}"

          Step 3: Run with vault password
          $ ansible-playbook installgitcurl.yml --ask-vault-pass

          Now your API key is:
          - Encrypted in git
          - Never exposed in plaintext
          - Properly secured!

    # -------------------------------------------------------------------------
    # TASK 11: Create example vault structure
    # -------------------------------------------------------------------------
    - name: Create example vault file structure (unencrypted demo)
      ansible.builtin.copy:
        content: |
          # EXAMPLE: This would be encrypted in real use!
          # Create this with: ansible-vault create vault.yml
          #
          # All secrets should be prefixed with 'vault_'

          # API Keys
          vault_openai_api_key: "sk-your-key-here"
          vault_github_token: "ghp_your-token-here"

          # Database credentials
          vault_db_password: "super_secret_db_password"
          vault_db_root_password: "even_more_secret"

          # SSH Keys (multi-line)
          vault_deploy_ssh_key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAA...
            -----END OPENSSH PRIVATE KEY-----

          # SSL Certificates
          vault_ssl_private_key: |
            -----BEGIN PRIVATE KEY-----
            MIIEvgIBADANBgkqhkiG9w0BAQ...
            -----END PRIVATE KEY-----
        dest: "{{ vault_demo_dir }}/vault_example.yml"
        mode: '0600'  # Restrictive permissions!

    - name: Create companion vars file
      ansible.builtin.copy:
        content: |
          # Non-sensitive variables
          # These reference the vaulted secrets

          # API Keys
          openai_api_key: "{{ vault_openai_api_key }}"
          github_token: "{{ vault_github_token }}"

          # Database
          db_host: "localhost"
          db_port: 5432
          db_user: "app_user"
          db_password: "{{ vault_db_password }}"  # References vault

          # Application settings
          app_name: "garden-agent"
          app_port: 8080
          debug_mode: false
        dest: "{{ vault_demo_dir }}/vars_example.yml"
        mode: '0644'

    # =========================================================================
    # MULTIPLE VAULT PASSWORDS
    # =========================================================================

    # -------------------------------------------------------------------------
    # TASK 12: Using multiple vault IDs
    # -------------------------------------------------------------------------
    - name: Show multiple vault passwords
      ansible.builtin.debug:
        msg: |
          MULTIPLE VAULT PASSWORDS:
          =========================

          Use different passwords for different environments!

          # Encrypt with vault ID
          ansible-vault encrypt --vault-id prod@prompt secrets_prod.yml
          ansible-vault encrypt --vault-id dev@prompt secrets_dev.yml

          # Run with multiple vault IDs
          ansible-playbook site.yml \
            --vault-id dev@~/.vault_pass_dev \
            --vault-id prod@~/.vault_pass_prod

          Use cases:
          - Dev team can't decrypt production secrets
          - Different security levels for different data

    # =========================================================================
    # SECURITY CHECKLIST
    # =========================================================================

    # -------------------------------------------------------------------------
    # TASK 13: Security best practices checklist
    # -------------------------------------------------------------------------
    - name: Display security checklist
      ansible.builtin.debug:
        msg: |
          VAULT SECURITY CHECKLIST:
          =========================

          [ ] Never commit unencrypted secrets
          [ ] Add .vault_pass to .gitignore
          [ ] Use strong vault passwords (20+ chars)
          [ ] Rotate vault passwords periodically
          [ ] Use different passwords for dev/prod
          [ ] Set restrictive file permissions (600)
          [ ] Use vault_password_file, not --ask-vault-pass in CI/CD
          [ ] Prefix vaulted vars with vault_
          [ ] Keep vault files separate from regular vars
          [ ] Audit who has vault password access

    # =========================================================================
    # SUMMARY
    # =========================================================================
    - name: List demo files
      ansible.builtin.find:
        paths: "{{ vault_demo_dir }}"
        patterns: "*"
      register: vault_files

    - name: Lesson Summary
      ansible.builtin.debug:
        msg:
          - "============================================"
          - "  VAULT SECRETS COMPLETE"
          - "============================================"
          - ""
          - "DEMO FILES: {{ vault_files.files | length }}"
          - ""
          - "KEY COMMANDS:"
          - "  ansible-vault create secrets.yml"
          - "  ansible-vault encrypt secrets.yml"
          - "  ansible-vault edit secrets.yml"
          - "  ansible-vault view secrets.yml"
          - "  ansible-vault decrypt secrets.yml"
          - "  ansible-vault encrypt_string 'secret'"
          - ""
          - "RUNNING PLAYBOOKS:"
          - "  ansible-playbook ... --ask-vault-pass"
          - "  ansible-playbook ... --vault-password-file .vault"
          - ""
          - "YOUR PROJECT CONNECTION:"
          - "  Secure your OPENAI_API_KEY in vault!"
          - "  Replace env lookup with vault reference."
          - ""
          - "CONGRATULATIONS!"
          - "  You've completed all 15 lessons!"
          - "  You now understand core Ansible concepts."
